/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function detailinputstreamfactory_create(a: number): number;
export function detailinputstream_close(a: number): void;
export function detailinputstream_send(a: number, b: number): void;
export function __wbg_detailinputstream_free(a: number): void;
export function __wbg_verse_free(a: number): void;
export function verse_new(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function verse_setMicAudioConstraints(a: number, b: number): void;
export function verse_isMicOn(a: number): number;
export function verse_micOn(a: number): number;
export function verse_micOff(a: number): void;
export function verse_isSpeakerOn(a: number): number;
export function verse_speakerOn(a: number): void;
export function verse_speakerOff(a: number): void;
export function verse_start(a: number): number;
export function verse_maxAvatarFileSize(a: number): number;
export function verse_maxNumberOfPeople(a: number): number;
export function verse_getDebugStatus(a: number, b: number): void;
export function verse_getDebugDistance(a: number, b: number): void;
export function __wbg_detailinputstreamfactory_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h951b505c4f39d0d8(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h48019296ec03b594(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h85133af50af7580c(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
